### PR TITLE
parse the context file

### LINKED ISSUE #27: Link to the preview environment is broken on main
I created a PR, but the message I got was pointing to https://github.com/#/previews/website-903-cindylopez, instead of to my okteto instance. 

My action looks like this:

```
on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@master
      with:
        url: https://staging.okteto.dev
        token: ${{ secrets.OKTETO_STAGING_TOKEN }}

    - name: "Deploy the preview environment"
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: website-${{ github.event.number }}-cindylopez
        scope: global
        timeout: 25m
        file: okteto-stack.yaml
```

I believe that the issue is with how https://github.com/okteto/deploy-preview/blob/master/message.go#L67 parses the token, this has changed due to `okteto context`

### PR DESCRIPTION
**Pull request by rberrelleza**
fixes #27

### CODE REVIEW

File: message.go [hunk 1]
```diff
@@ -9,14 +9,13 @@ import (
...
-	Username  string `json:"Username"`
-	Token     string `json:"Token"`
-	MachineID string `json:"MachineID"`
+type contexts struct {
+	Current  string             `json:"current-context"`
+	Contexts map[string]context `json:"contexts"`
+}
+
+type context struct {
+	Name string `json:"name"`
```
Comment (rberrelleza) [inline message.go:18]: since this is the only thing we need, I figure it might be easier to just parse that.

**Review by pchico83 — APPROVED** [review]

**Review by jLopezbarb — APPROVED** [review]
